# Generated by Django 4.2.25 on 2026-09-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='DATE')),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('mobile_no', models.CharField(db_column='MOBILE_NO', max_length=15)),
                ('alternate_no', models.CharField(blank=True, db_column='ALTERNATE_NO', max_length=20, null=True)),
                ('email_id', models.CharField(blank=True, db_column='EMAIL_ID', max_length=50, null=True)),
                ('address', models.TextField(blank=True, db_column='ADDRESS', null=True)),
                ('course', models.CharField(db_column='COURSE', max_length=50)),
                ('batch', models.CharField(blank=True, db_column='BATCH', max_length=30, null=True)),
                ('experience_fresher', models.CharField(blank=True, db_column='EXPERIENCE_FRESHER', max_length=30, null=True)),
                ('how_you_know', models.CharField(blank=True, db_column='HOW_YOU_KNOW', max_length=50, null=True)),
                ('contact', models.CharField(blank=True, db_column='CONTACT', max_length=50, null=True)),
                ('counselor', models.CharField(blank=True, db_column='COUNSELOR', max_length=50, null=True)),
                ('fees', models.IntegerField(db_column='FEES', default=0)),
                ('comment', models.TextField(blank=True, db_column='COMMENT', null=True)),
                ('selected_type', models.CharField(blank=True, db_column='SELECTED_TYPE', max_length=30, null=True)),
            ],
            options={
                'db_table': 'student_details',
                'managed': True,
            },
        ),
    ]
